<?php
/**
 * Secrets, encryption at rest (AES-256-GCM via OpenSSL) and HMAC signing.
 *
 * The keys live in data/secret.php, generated by the installer. That file is
 * outside the web root when the recommended layout is used, is denied by
 * .htaccess otherwise, and is excluded from version control (.gitignore).
 * Losing it means the SMTP password must be typed again and all pending
 * links (unsubscribe links in e-mails already sent included) stop working.
 */
final class Crypto
{
    private static $keys = null;

    private static function keys(): array
    {
        if (self::$keys === null) {
            if (!is_file(NM_SECRET_FILE)) {
                throw new RuntimeException('Missing secret file: ' . NM_SECRET_FILE);
            }
            $k = require NM_SECRET_FILE;
            if (!is_array($k) || empty($k['enc_key']) || empty($k['hmac_key'])) {
                throw new RuntimeException('Invalid secret file: ' . NM_SECRET_FILE);
            }
            self::$keys = [
                'enc' => base64_decode($k['enc_key'], true),
                'hmac' => base64_decode($k['hmac_key'], true),
            ];
            if (strlen((string) self::$keys['enc']) !== 32 || strlen((string) self::$keys['hmac']) !== 32) {
                throw new RuntimeException('Invalid key length in ' . NM_SECRET_FILE);
            }
        }
        return self::$keys;
    }

    /** Writes a new data/secret.php with random keys. Refuses to overwrite. */
    public static function generateSecretFile(): void
    {
        if (is_file(NM_SECRET_FILE)) {
            return;
        }
        $content = "<?php\n"
            . "// Notify Me List — secret keys generated on " . gmdate('Y-m-d H:i:s') . " UTC.\n"
            . "// KEEP THIS FILE PRIVATE. Do not commit it, do not share it.\n"
            . "// Deleting it invalidates the stored SMTP password and all links already e-mailed.\n"
            . "if (!defined('NM_ROOT')) { http_response_code(403); exit; }\n"
            . "return [\n"
            . "    'enc_key' => '" . base64_encode(random_bytes(32)) . "',\n"
            . "    'hmac_key' => '" . base64_encode(random_bytes(32)) . "',\n"
            . "];\n";
        if (@file_put_contents(NM_SECRET_FILE, $content, LOCK_EX) === false) {
            throw new RuntimeException(t('install.cannot_write', ['file' => NM_SECRET_FILE]));
        }
        @chmod(NM_SECRET_FILE, 0600);
        self::$keys = null;
    }

    public static function encrypt(string $plain): string
    {
        if ($plain === '') {
            return '';
        }
        $iv = random_bytes(12);
        $tag = '';
        $cipher = openssl_encrypt($plain, 'aes-256-gcm', self::keys()['enc'], OPENSSL_RAW_DATA, $iv, $tag, 'nm-v1', 16);
        if ($cipher === false) {
            throw new RuntimeException('Encryption failed');
        }
        return 'v1:' . base64_encode($iv . $tag . $cipher);
    }

    public static function decrypt(string $stored): string
    {
        if ($stored === '') {
            return '';
        }
        if (strpos($stored, 'v1:') !== 0) {
            throw new RuntimeException('Unknown encrypted value format');
        }
        $raw = base64_decode(substr($stored, 3), true);
        if ($raw === false || strlen($raw) < 29) {
            throw new RuntimeException('Corrupted encrypted value');
        }
        $plain = openssl_decrypt(substr($raw, 28), 'aes-256-gcm', self::keys()['enc'], OPENSSL_RAW_DATA, substr($raw, 0, 12), substr($raw, 12, 16), 'nm-v1');
        if ($plain === false) {
            throw new RuntimeException('Decryption failed (wrong key?)');
        }
        return $plain;
    }

    /** URL-safe HMAC-SHA256 signature of $data, truncated to $bytes. */
    public static function sign(string $data, int $bytes = 16): string
    {
        return nm_b64url_encode(substr(hash_hmac('sha256', $data, self::keys()['hmac'], true), 0, $bytes));
    }

    public static function verify(string $data, string $signature, int $bytes = 16): bool
    {
        return hash_equals(self::sign($data, $bytes), $signature);
    }

    /** Hash used to store tokens (keyed, so a DB leak alone is useless). */
    public static function tokenHash(string $token): string
    {
        return hash_hmac('sha256', 'token|' . $token, self::keys()['hmac']);
    }
}
